# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  currentDate: $[upper(format('{0:MMddyy}-{1}', pipeline.startTime, $(Rev:.r)))]
  buildNumber: $(Build.BuildNumber)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\MBBSEmu.csproj'
    arguments: '--output $(Build.BinariesDirectory)\publish\win-x64\ --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --verbosity n'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\MBBSEmu.csproj'
    arguments: '--output $(Build.BinariesDirectory)\publish\win-x86\ --runtime win-x86 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --verbosity n'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\MBBSEmu.csproj'
    arguments: '--output $(Build.BinariesDirectory)\publish\linux-x64\ --runtime linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --verbosity n'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\MBBSEmu.csproj'
    arguments: '--output $(Build.BinariesDirectory)\publish\linux-arm\ --runtime linux-arm --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --verbosity n'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\MBBSEmu.csproj'
    arguments: '--output $(Build.BinariesDirectory)\publish\osx-x64\ --runtime osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --verbosity n'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\publish\win-x64'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BinariesDirectory)\publish\zipped\mbbsemu-win-x64-$(currentDate).zip'
    replaceExistingArchive: true
    verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\publish\win-x86'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BinariesDirectory)\publish\zipped\mbbsemu-win-x32-$(currentDate).zip'
    replaceExistingArchive: true
    verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\publish\linux-x64'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BinariesDirectory)\publish\zipped\mbbsemu-linux-x64-$(currentDate).zip'
    replaceExistingArchive: true
    verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\publish\linux-arm'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BinariesDirectory)\publish\zipped\mbbsemu-linux-arm-$(currentDate).zip'
    replaceExistingArchive: true
    verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\publish\osx-x64'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BinariesDirectory)\publish\zipped\mbbsemu-osx-x64-$(currentDate).zip'
    replaceExistingArchive: true
    verbose: true


- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.BinariesDirectory)\publish\zipped'
    azureSubscription: 'Primary Azure Subscription(95c13f74-9879-4506-b31c-224e0bcf5230)'
    Destination: 'AzureBlob'
    storage: 'mbbsemu'
    ContainerName: '$web\builds\$(currentDate)'